[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.7.5"
tokio = {version = "1.0", features = ["full"]}
tracing-subscriber = "0.3.11"
tracing = "0.1.33"
serde = {version = "1.0", features = ["derive"]}
