[package]
name = "chat-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.37.0", features = ["full"]}
async-trait = "0.1"
futures = "0.1.31"
libp2p = { version = "0.53.2", features = [ "tokio", "gossipsub", "mdns", "noise", "macros", "tcp", "yamux", "quic"] }
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}