[package]
name = "dioxus-live"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1"
dioxus = {version = "0.1", features = ["web"] }
tracing-wasm = "0.2"
wasm-bindgen = "0.2"
tracing = "0.1.40"
